### ISSUE TITLE
music control not showing on iOS

### ISSUE THREAD

**Issue by Andriah91** [ingageco/capacitor-music-controls-plugin-for-capacitor-2#20]
Hello, I'm using howler to play audio. I use capacitor-music-controls-plugin to control media from background and it works well with android but not for iOS. 
I've tried to use Media (native media) and it works above iOS and android but i don't want to use native Media.
Thanks for your help.
![Capture d’écran 2021-02-18 à 11 36 20](https://user-images.githubusercontent.com/12873065/108321410-8d768d00-71dd-11eb-9ce4-34d85729810f.png)

**Comment by mickiestorm** [comment]
Sounds like you might need to enable background mode in your app to be able to access event listeners etc. while in background mode? 

It works fine for me on iOS, so maybe I can help you debug the issue?

**Comment by shira164** [comment]
Hello!
It doesn't show up for me either and I have background mode audio enabled. did you get it to show up on iOS?

**Comment by mickiestorm** [comment]
@shira164 
It works perfectly fine for iOS in my app. I haven't gotten to Android yet, so I can only speak for iOS. 
Are you running it on a device or emulator? I would suggest testing on a device and try to strip down as many of the setup options as possible as you test it.

You might also want to either get a plugin to print all console messages to XCode or debug using this guide:
https://ionic.zone/debug/remote-debug-your-app

... XCode's Console won't display all errors otherwise. This might give you a bit more information about what is up :)

**Comment by shira164** [comment]
@mickiestorm 
Xcode shows me the following error.
`Error acquiring assertion: <Error Domain=RBSAssertionErrorDomain Code=3 "Required client entitlement is missing" UserInfo={RBSAssertionAttribute=<RBSDomainAttribute| domain:"com.apple.webkit" name:"MediaPlayback" sourceEnvironment:"(null)">, NSLocalizedFailureReason=Required client entitlement is missing}`
![image](https://user-images.githubusercontent.com/61434028/128685483-1530b76b-a5db-4474-85a4-295f4fdb3feb.png)

![image](https://user-images.githubusercontent.com/61434028/128697428-c8fee913-4eed-40c3-bc5e-beb6b8b390f9.png)
